<?php

namespace Syntax\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    
    public function getTotal() {
        $qb = $this->createQueryBuilder('a')
                        ->select('COUNT(a)');
        
        return (int) $qb->getQuery()->getSingleScalarResult();
    }
}